version: "2.2"

services:
    es01:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
      container_name: elasticsearch01
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elastic-demo-data-01:/usr/share/elasticsearch/data
      ports:
        - 127.0.0.1:9200:9200
      networks:
        - elastic

    kibana:
      image: docker.elastic.co/kibana/kibana:7.15.1
      container_name: kibana
      ports:
        - 5601:5601
      environment:
        ELASTICSEARCH_URL: http://es01:9200
        ELASTICSEARCH_HOSTS: http://es01:9200
      networks:
        - elastic

volumes:
  elastic-demo-data-01:
    driver: local
networks:
    elastic:
      driver: bridge